"""initial

Revision ID: cb001ae4f726
Revises: 
Create Date: 2026-03-25 01:51:35.962123

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cb001ae4f726'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_data',
    sa.Column('username', sa.String(length=100), nullable=False),
    sa.Column('email_id', sa.String(length=200), nullable=False),
    sa.Column('password', sa.Text(), nullable=False),
    sa.PrimaryKeyConstraint('email_id')
    )
    op.create_table('user_expenses',
    sa.Column('expense_id', sa.Integer(), nullable=False),
    sa.Column('email_id', sa.String(length=200), nullable=False),
    sa.Column('category', sa.String(length=100), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('expense_name', sa.String(length=100), nullable=False),
    sa.Column('expense_amount', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['email_id'], ['user_data.email_id'], ),
    sa.PrimaryKeyConstraint('expense_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user_expenses')
    op.drop_table('user_data')
    # ### end Alembic commands ###
